name: Rben Cstel
favicon: null
layout_spectrum: 0.14696608064696193
typography_spectrum: 0.45881519140675664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.716571751749143
  lightness: 0.9748659676406533
  saturation: 0.698087879223749
  rhythmicContrast: 0.18423933978192508
purpose: []
