name: Rben Cstel
favicon: null
layout_spectrum: 0.39262
typography_spectrum: 0.22341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#17100a'
    - '#34302b'
    - '#73706d'
    - '#bcbab8'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
