name: Rben Cstel
favicon: null
layout_spectrum: 0.0638
typography_spectrum: 0.22341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#17100a'
    - '#34302b'
    - '#73706d'
    - '#bcbab8'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
