name: Rben Cstel
favicon: null
layout_spectrum: 0.88584
typography_spectrum: 0.45881519140675664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2d3c'
    - '#49515c'
    - '#7c8089'
    - '#d7d2bf'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
